### ISSUE TITLE
relation查询问题

### ISSUE THREAD

**Issue by meredith233** [bmob/hydrogen-js-sdk#11]
在进行relation查询时，代码如下
const query = Bmob.Query('_User')
query.field('f', wx.getStorageSync('userid'))
query.relation('infoPic').then(res => {
    console.log(res)
})
会出现404notfound
会发现此时查询的链接也
https://api.bmobcloud.com/1/infoPic?where=%7B%22%24relatedTo%22%3A%7B%22object%22%3A%7B%22__type%22%3A%22Pointer%22%2C%22className%22%3A%22_User%22%2C%22objectId%22%3A%22ce4c655f0f%22%7D%2C%22key%22%3A%22f%22%7D%7D

而正常情况下，查询链接应该为
https://api.bmobcloud.com/1/classes/infoPic?    开头

故而发现
query.relation('classes/infoPic').then(res => {
此处应填写'classes/infoPic'才能正常查询relation

**Comment by magic007** [comment]
更新下1.6.1  之前只兼容了用户表
