### ISSUE TITLE
查询所有

### ISSUE THREAD

**Issue by s3hengwu** [bmob/hydrogen-js-sdk#12]
查询所有返回的res，要怎么遍历啊
 for (var i = 0; i < res.length; i++) {
        let object = res[i];
}
这样写报错

**Comment by magic007** [comment]
不需要遍历啊， 这里遍历你只是想循环打印出来看看吧

**Comment by s3hengwu** [comment]
希望可以有更详细一点的demo。用回旧版小程序文档了

**Comment by magic007** [comment]
新版我们也有一个详细的DEMO https://github.com/bmob/wechatapp-demo
