### ISSUE TITLE
新版小程序下查询Relation问题

### ISSUE THREAD

**Issue by suyuqian** [bmob/hydrogen-js-sdk#13]
新版微信小程序下：Relation查询时，field方法限定条件后无法返回查询结果：
    let current = wx.Bmob.User.current();
    const query = wx.Bmob.Query("oder");
    query.field("dcUsers", current.objectId);//这里在oder数据表里有dcUsers字段，为Relation类型，里面有相应的objectId
    query.relation("_User").then(res => {
      console.log(res);//返回{count: 0, results: Array(0)}，我想返回的结果时dcUsers里含有查询objectId的所有数据
    })
请问是哪里出了问题？

**Comment by magic007** [comment]
objectId 是当前记录的objectId，不是关联表的记录ID

**Comment by suyuqian** [comment]
非常感谢你magic007，菜鸟的我修改了好多个地方，就是没改到这里，能否告诉我反向查询的方法，即如何查询一个用户的所有发布记录？
