### ISSUE TITLE
只支持小程序吗，怎么用纯HTML+JS+jQuery开发

### ISSUE THREAD

**Issue by bzsome** [bmob/hydrogen-js-sdk#17]

**Comment by magic007** [comment]
https://www.jianshu.com/p/4f9fdf956bb8  这里有个简单教程

**Comment by bzsome** [comment]
支持普通html的bmob.js在哪儿下载呢？这个项目中的bmob.js不能直接使用。

**Comment by bzsome** [comment]
bmob.js

> https://www.jianshu.com/p/4f9fdf956bb8 这里有个简单教程

支持普通html的bmob.js在哪儿下载呢？这个项目中的bmob.js不能直接使用。

**Comment by yanghuanrong** [comment]
可以直接script的方式引入。

**Comment by yanghuanrong** [comment]
我这边测试 <script src="./Bmob-1.6.3.min.js" charset="utf-8"></script> 这种方式是可行的。

**Comment by bzsome** [comment]
1.0 的js文件可以正常使用，且测试成功。但是其他版本的不能正常使用。

**Comment by bzsome** [comment]
1.0版本 Bmob-1.6.3.min.js的文件可以正常使用，且测试成功。但是其他版本的不能正常使用。
这是1.0版本的截图
![tim 20180914113045](https://user-images.githubusercontent.com/35402969/45528166-b5de4e00-b811-11e8-8ddb-3136a5bd2427.png)

**Comment by yanghuanrong** [comment]
你发的这个是旧版本的js-sdk  不支持import方式
新版本的混合sdk 是支持的，建议使用新版本的

**Comment by bzsome** [comment]
新版本这是报错了，
[Web浏览器] "Uncaught SyntaxError: Invalid left-hand side in assignment"	/bmobTest/dist/Bmob-1.6.3.min.js (36)
![tim 20180914113458](https://user-images.githubusercontent.com/35402969/45528337-5f254400-b812-11e8-8557-b7e36bb42d63.png)

**Comment by yanghuanrong** [comment]
这应该是不支持es6语法造成的。

**Comment by bzsome** [comment]
尝试使用es6，但仍然报错
![tim 20180914114048](https://user-images.githubusercontent.com/35402969/45528508-1de16400-b813-11e8-8b8a-7f31959e27c7.png)

**Comment by bzsome** [comment]
已确认JS文件可以直接引入，用Chrome打开Html不会报错。只是HBuilder会对Bmob-1.6.3.min.js格式化后的第36行报错。

**Comment by yanghuanrong** [comment]
我这边测试在谷歌浏览器中bmob-1.6.3.js 会正常运行，HBuilder会对Bmob-1.6.3.min.js格式化后的第36行报错，这个可能是HBuilder 语法提示造成的。 我这边使用的是ATOM 不会出现这个问题。
