### ISSUE TITLE
请教一下，在使用npm安装hydrogen-js-sdk之后，在初始化的时候，报错说找不到文件

### ISSUE THREAD

**Issue by lawushanshan** [bmob/hydrogen-js-sdk#20]
![tim 20180918091722](https://user-images.githubusercontent.com/23500340/45658779-acabf480-bb23-11e8-83f9-ac6f8f520904.png)
![qq 20180918091830](https://user-images.githubusercontent.com/23500340/45658816-dcf39300-bb23-11e8-8290-1f03e0c8032f.png)

**Comment by lawushanshan** [comment]
npm安装的版本为hydrogen-js-sdk@1.6.4

**Comment by bhk545145** [comment]
请问你解决了吗，我也碰到了同样的问题
