### ISSUE TITLE
localStorage is not defined

### ISSUE THREAD

**Issue by bhk545145** [bmob/hydrogen-js-sdk#22]
npm 导入后，运行报错，localStorage is not defined，
npm install localStorage后也没有用

**Comment by MaoHui2016** [comment]
我也是这个问题can't find variable:localStorage，我是用react-native 开发App,安装bomb，npm install hydrogen-js-sdk，安装完成之后引入bomb,出现can't find variable:localStorage

**Comment by miaoMiaoDaShi** [comment]
我今天也遇到了同样的问题,react-native,,,,,,,,,,,,
![image](https://user-images.githubusercontent.com/22437662/53940037-943e8f00-40ef-11e9-97f8-f9897981a739.png)

**Comment by miaoMiaoDaShi** [comment]
该问题是因为reactNative里没有找到localStorage导致的,问题的解决方法如下

- 1.导入localStorage,并在Bmob-x.x.x,js中进行配置.

我是直接复制到和Bmob-x.x.x,js同目录的,完美解决问题.
贴出一下代码啦.
`  const {isString: r} = n(2);
        let o;
        //这里很关键,注意啦
        localStorage = require('localStorage')
        o = "undefined" != typeof cc ? cc.sys.localStorage : localStorage; `
