### ISSUE TITLE
Cannot find module '../../node_modules/axios/index'

### ISSUE THREAD

**Issue by chenby** [bmob/hydrogen-js-sdk#23]
`npm i  hydrogen-js-sdk`
`import Bmob from "hydrogen-js-sdk";`
就报错了。
能不能把sdk做好再上线产品？这不是坑人吗

**Comment by chenby** [comment]
require github上的Bmob-1.6.4.min.js，又出错。
TypeError: "xxrequire('@system.fetch')xx".fetch is not a function

**Comment by chenby** [comment]
查了下是引用axios包的时候，直接require('../../node_modules/axios/index'),包依赖不在当前包路径下。
npm3之后就不敢这么用了。现在还这么写？

**Comment by magic007** [comment]
问题一：
不好意思， 这个是快应用的一个网络请求库，由于可能存在报错，所以用字符拼接起来了。 "xxrequire('@system.fetch')xx".f


问题2：
axios  这个需要进入SDK npm install axios

**Comment by chenby** [comment]
哪有node模块需要跑到包里install的？
这块sdk直接改成require（“axios”）就行。

**Comment by magic007** [comment]
> 这个还没人改？

改了哈，1.6.6

**Comment by Fatpigs** [comment]
1.6.6还是  require('@system.fetch')".fetch 报错  这个应该怎么解决？

**Comment by Fatpigs** [comment]
Node  XMLHttpRequest is not defined 要怎么做

**Comment by magic007** [comment]
> Node XMLHttpRequest is not defined 要怎么做

使用这个库，你这个提示是之前5年前的库。
