### ISSUE TITLE
为什么我引入任何一个版本的SDK都不行啊？

### ISSUE THREAD

**Issue by Heart-King** [bmob/hydrogen-js-sdk#24]
提示“”Cannot read property 'extend' of undefined;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: Cannot read property 'extend' of undefined“，但是我从百度上下载了一个源码版的bmob.js就可以用，什么情况？你这个SDK是可以供小程序使用嘛。

**Comment by magic007** [comment]
是提供小程序的，你百度下载的那个是旧版SDK。 旧版SDK语法里才有extend。


你这里下载的是新版SDK， 应该看新版开发文档。  目前你看错了开发文档

**Comment by Heart-King** [comment]
已结解决，感谢回答！
