### ISSUE TITLE
nodejs里登录成功，获取当前用户还是空的啊

### ISSUE THREAD

**Issue by s3hengwu** [bmob/hydrogen-js-sdk#25]
Bmob.User.login(name, password).then(response => {
        console.log("登录成功"+response);
        //获取用户当前信息
        let current = Bmob.User.current();
        if(current == null) {
          console.log("用户数据是空的");
        }
        
        req.session.user = current;
        res.redirect('/');
      }).catch(err => {
        res.render('login', {message: err.error});
     });

**Comment by magic007** [comment]
是的，node没有用session库，没有用 session 把登陆信息自动保存起来，麻烦你手动保存下。
