### ISSUE TITLE
说一下发现的问题

### ISSUE THREAD

**Issue by BoolTrue** [bmob/hydrogen-js-sdk#3]
1.目前的很多方法都很局限性
    比如：destroyAll，saveAll 等批量的方法都只能在find回调里面使用。保存和更新的save也只能在get方法之后使用。
2.Pointer类型的支持相比老版本的要差很多
    老版本的pointer很好理解  要关联对象只需set进去一个带有objectId的对象就能直接关联起来。而现在只能重新构建一个_type=Pointer的对象，并且把objectId设置好才行  这样有时候再做保存更新的时候会多出来一步操作。
3.上传文件返回的对象没有_type属性 
    同第二点没有type属性，在做文件关联的时候还是要重新构造一下__type 。 像这样：
`nessImgTemp.img.__type = 'File';
`
4.对于array的支持也不太好
   更新，删除都很麻烦，必须先get才行，最好是获取到objectId就可以直接进行更新，修改，删除等操作

**Comment by 18978909244** [comment]
新版本查询Pointer类型为指定自己的最佳实践是什么？文档都没写。。。

**Comment by magic007** [comment]
1. saveAll 谢谢帮忙重写了

2. Pointer与file，后面我们会写个函数让实例化使用

3.文件上传关联也会写个函数让实例化使用


4. array的操作延续了旧SDK的使用法，后面有时间考虑是否增加您建议的。

**Comment by magic007** [comment]
新版本查询Pointer类型为指定自己的最佳实践是什么？文档都没写。。。

新版文档有写如果查出关联表。
示例代码如下
const query = Bmob.Query('tableName');
//下面参数为Pointer字段名称， 可以一次查询多个表
query.include('own','post')
query.find().then(res => {
    console.log(res)
  }).catch(err => {
    console.log(err)
  })

**Comment by BoolTrue** [comment]
感谢耐心回复
