### ISSUE TITLE
can't find variable:localStorage

### ISSUE THREAD

**Issue by MaoHui2016** [bmob/hydrogen-js-sdk#30]
我是用react-native 开发App,安装bomb，npm install hydrogen-js-sdk，安装完成之后引入bomb,出现can't find variable:localStorage

**Comment by magic007** [comment]
暂时不支持react-native ，不好意思，react-native建议直接调用restful

**Comment by duanpf** [comment]
我想问下，不支持的意思，就是react-native中不能使用bmob吗？还是不支持npm下载？
