### ISSUE TITLE
分组统计结果排序不起作用

### ISSUE THREAD

**Issue by suyuqian** [bmob/hydrogen-js-sdk#31]
query.statTo("sum", "point");
query.statTo("groupby", "user");
query.statTo("order", "-_sumPoint");
无论如何设置，查询结果都不能排序

**Comment by magic007** [comment]
收到，这边测试下

**Comment by magic007** [comment]
测试了，可以分组后排序，  //结果排序
  query.order("-createdAt");
  query.statTo("groupby", "title");  测试这个结果是可以的，最新1.6.7 SDK
