### ISSUE TITLE
条件查询无效

### ISSUE THREAD

**Issue by snsogbl** [bmob/hydrogen-js-sdk#32]
代码如下:
![image](https://user-images.githubusercontent.com/5416723/53708346-f7b98a00-3e6d-11e9-9d96-4e0910f7a8d1.png)
结果如下：
![image](https://user-images.githubusercontent.com/5416723/53708417-554dd680-3e6e-11e9-8a65-7200b04d0dc4.png)
表数据如下:
![image](https://user-images.githubusercontent.com/5416723/53708432-6dbdf100-3e6e-11e9-9486-cf79e6975d9a.png)

**Comment by magic007** [comment]
看下网络请求是否带入参数。
