### ISSUE TITLE
小程序最新js-sdk不能在数据库创建数据

### ISSUE THREAD

**Issue by xiaohupei** [bmob/hydrogen-js-sdk#34]
console.log(Bmob)
var Event = Bmob.Object.extend("event");
 let event = new Event();

小程序IDE报错，但是打印出来的Bmob是有的，但是没有Object，是不是修改了创建数据的方法，但是没有修改文档？

还有个问题就是最新的js-sdk包含了websocket吗，不需要引入websocket 的js文件了吗，还是按文档操作？
Cannot read property 'extend' of undefined;

**Comment by magic007** [comment]
你看错文档了， 请看官网小程序新文档。
