### ISSUE TITLE
vue-cli3 中使用 code: 10007 error: "AppKey is empty"

### ISSUE THREAD

**Issue by maplehsu** [bmob/hydrogen-js-sdk#36]
按照官网教程引入
// 安装
npm install hydrogen-js-sdk

// 打开 main.js
import Bmob from "hydrogen-js-sdk";

// 初始化 SDK版本 2.0.0 以下保留之前的初始化方法
Bmob.initialize("你的Application ID", "你的REST API Key");

但是调用的时候一直提示这个错误。

**Comment by maplehsu** [comment]
加密有问题。

**Comment by magic007** [comment]
你SDK 最新版， 初始化不是Bmob.initialize("你的Application ID", "你的REST API Key");  你看bmob.cn文档，初始化key已经改了
