### ISSUE TITLE
bmob.js里面的初始化提示判断条件

### ISSUE THREAD

**Issue by xiaofuyesnew** [bmob/hydrogen-js-sdk#37]
文件里面的提示判断条件好像有问题，导致总是提示初始化失败。

```javascript
Bmob.initialize = (secretKey, securityCode, masterKey) => {
  if (securityCode > 6) { //这里的判断条件好像应该是securityCode.length > 6
    console.log(`Bmob初始化失败，2.0版本SDK请使用API安全码初始化，文档地址：https://bmob.github.io/hydrogen-js-sdk/#/?id=初始化`)
  }
  Bmob._config.secretKey = secretKey
  Bmob._config.securityCode = securityCode
  Bmob._config.applicationMasterKey = masterKey
}
```

**Comment by magic007** [comment]
不好意思，少写了个长度属性

**Comment by magic007** [comment]
已经修复，非常抱歉。

**Comment by xiaofuyesnew** [comment]
@magic007 我惊呆了，如果这个参数不传呢？`.length`明显会报错的，窃以为这里的严格判断条件是`!securityCode || securityCode.length > 6`，仅供参考。

**Comment by magic007** [comment]
恩恩，这里多加个判断为空也没错。 不过目前大家都会传2个key。  主要是这次变动传的key，很多人还不知道已经换成api安全key，所以这里方便大家，价格提示语句。 如果真有多人不传第二个值，找到我，我肯定也会把第一个第二个值判断下。

感谢建议。

**Comment by magic007** [comment]
恩恩，这里多加个判断为空也没错。 不过目前大家都会传2个key。 主要是这次变动传的key，很多人还不知道已经换成api安全key，所以这里方便大家，加个提示语句。 如果真有多人不传第二个值，找到我，我肯定也会把第一个第二个值判断下。

感谢建议。
