### ISSUE TITLE
预览上传的图片报 invisible domain

### ISSUE THREAD

**Issue by foreverZ133** [bmob/hydrogen-js-sdk#38]
使用 web 文件上传，可得到结果数组，
但想预览此图时，报 invisible domain，如图：
![image](https://user-images.githubusercontent.com/22021589/63009975-1e1d3000-beb8-11e9-95b7-292f548bda8b.png)
http://bmob-cdn-26728.b0.upaiyun.com/2019/08/14/063be2ed40dd13588060561914c69238.png

是否是 bmob 在又拍云下被限制了，那我该如何寻找替代方案。

_另外，还有个小问题，多次上传同个素材，会素材管理界面会显示多个同名文件。_

**Comment by magic007** [comment]
在应用设置，绑定自己域名。 

另外的问题，上传同个素材，正式网络路径是不一样的，你上传成功，把路径保存到表里。无需管素材页面
