### ISSUE TITLE
node 环境下报 "require('@system.fetch')".fetch is not a function

### ISSUE THREAD

**Issue by foreverZ133** [bmob/hydrogen-js-sdk#40]
如图：
![image](https://user-images.githubusercontent.com/22021589/65500615-25415000-def2-11e9-8804-a5846344e851.png)

环境：
Bmob-2.2.0.min.js
node v10.2.0
npm 6.11.3
Windows 7 旗舰版

**Comment by magic007** [comment]
这个是在浏览器环境下运行， 如果还有疑问，麻烦联系下我QQ，谢谢
------------------
Best regards
magic.peng (谭鹏）
QQ:730170034

**Comment by magic007** [comment]
node  应该也是用这个， bmob/hydrogen-js-sdk  ，目前不能用吗？
------------------
Best regards
magic.peng (谭鹏）
mob:13422051506

**Comment by foreverZ133** [comment]
现在是从 bmob/hydrogen-js-sdk 下载的 Bmob-2.2.0.min.js 然后直接引用的

**Comment by magic007** [comment]
已经解决了，麻烦再试试
