### ISSUE TITLE
云函数

### ISSUE THREAD

**Issue by Jackzhng** [bmob/hydrogen-js-sdk#43]
您好，我最近写小程序调用bmob云函数时，小程序报错：Cannot read property 'run' of undefined。
小程序中调用的函数如下：test:function(){
    console.log(Bmob)
    Bmob.Cloud.run('test', {}, {
      success: function (result) {
        alert(result);
      },
      error: function (error) {
      }
    })
我检查错误的时候，用控制台打印出Bmob,发现并没有cloud这一属性。请问是什么问题呢？

**Comment by 85u2e8** [comment]
xxxisnotdefined

**Comment by magic007** [comment]
看下这个文档， 新版文档已经不是run了。

**Comment by magic007** [comment]
http://doc.bmob.cn/data/wechat_app_new/index.html#_95
