### ISSUE TITLE
验证码登录问题

### ISSUE THREAD

**Issue by caiwenglong** [bmob/hydrogen-js-sdk#49]
发送验证码的时候是6位数字，在通过验证码登录的时候，进行验证码验证的时候，要求用Number类型，js在转number类型的时候 前面的0会被清掉（比如： ‘’023231‘） 转为number类型是23231，这样验证码会不通过，导致验证失败。

**Comment by magic007** [comment]
验证码要求传入的是string呀，麻烦看下文档，文档地址帮你找出来了，地址连接：
http://doc.bmob.cn/data/wechat_app_new/index.html#_95
