### ISSUE TITLE
1.4.2构建缺少依赖包axios

### ISSUE THREAD

**Issue by hugzh** [bmob/hydrogen-js-sdk#6]
是的，1.4.2 后面提交了一次，包含了axios包，你目前可以看到里面有。  npm install hydrogen-js-sdk 目前axios包还没更新上去

**Comment by magic007** [comment]
是的，1.4.2 后面提交了一次，包含了axios包，你目前可以看到里面有。 npm install hydrogen-js-sdk 目前axios包还没更新上去
