### ISSUE TITLE
类型文件似乎存在一个错误

### ISSUE THREAD

**Issue by Thulof** [bmob/hydrogen-js-sdk#62]
export interface BmobPromise<T = any> extends Promise<BmobPromise<T>> {
}

似乎应该为

export interface BmobPromise<T = any> extends Promise<T> {
}

**Comment by magic007** [comment]
你这个说的不是这个SDK吧？

**Comment by 97Yates05** [comment]
类型文件似乎存在很多错误。。tsc命令有十几个错误，无法正常打包

**Comment by yanghuanrong** [comment]
类型文件错误是比较多。目前正在ts 重构中。
