### ISSUE TITLE
初始化错误： 签名安全验证错误

### ISSUE THREAD

**Issue by miragelu-seekasia** [bmob/hydrogen-js-sdk#63]
{ code: 400, error: '签名安全验证错误' }
我html引用Bmob-x.x.x.min.js没问题，nodejs使用你的这个plugin时报错

**Comment by IShinji** [comment]
相同问题

**Comment by IShinji** [comment]
> { code: 400, error: '签名安全验证错误' }
> 我html引用Bmob-x.x.x.min.js没问题，nodejs使用你的这个plugin时报错

今天试了一下 2.2.2 可以用，先降版本凑合用吧。

**Comment by magic007** [comment]
非常抱歉，服务端版本问题，已经修复。麻烦再试试
