### ISSUE TITLE
JS 短信登录 API 输入参数校验问题

### ISSUE THREAD

**Issue by sunjq1996** [bmob/hydrogen-js-sdk#65]
短信登录API signOrLoginByMobilePhone 函数要求输入的短信验证码 smsCode 类型必须为 Number，如果收到的6位短信验证码以0或00开头，那么传入的Number就会变成自动变成5位或4位，这时接口会返回验证码错误。

实际测试时，遇到这种情况，控制台获取的前端向服务器发起的GET请求中 smsCode参数确实会变成不足6位，导致验证码错误。

同样的情况下，如果我把sdk中对 smsCode 的类型校验修改为 String并传入完整的6位字符串类型短信验证码，则不会报错，可以正常登陆。

**Comment by magic007** [comment]
这个问题需要修改后端，这边跟同事反馈下，这个参数改为字符型。
