### ISSUE TITLE
文件上传无法自定义文件名

### ISSUE THREAD

**Issue by HeZongyao** [bmob/hydrogen-js-sdk#66]
Bmob.min.js中的{name:t,route:f._config.parameters.FILES+"/"+f._config.secretKey+"."+r,data:n}会导致上传文件名固定为secretKey+拓展名，修改为{name:t,route:f._config.parameters.FILES+"/"+t,data:n}之后可以在调用dataURLtoFile()时自定义文件名。

**Comment by magic007** [comment]
真实文件名是没法自定义的，备注文件名是可以固定为secretKey+拓展名，或者你自己改下代码，自定义下这个名字
