### ISSUE TITLE
微信小程序   新版 sdk，date类型读取结果 很奇怪

### ISSUE THREAD

**Issue by ehcsa** [bmob/hydrogen-js-sdk#7]
bmob数据库中其中一个date字段返回值的结构和系统自动生成的createdAt不一样，如下:

  createdAt:"2018-05-21 16:21:55"
enddate:{__type: "Date", iso: "2018-05-21 17:00:00"}                     

保存和读取都  遇到了问题

**Comment by magic007** [comment]
恩，日期类型保存，他是一个json，这样  {__type: "Date", iso: "2018-05-21 17:00:00"} ， createdAt本身也是一个json，只是我们转义了。

**Comment by ehcsa** [comment]
旧版sdk 好像都有转义，能否将date类型都默认转义

**Comment by magic007** [comment]
SDK里面不能，因为我们不知道你哪个字段是日期字段类型。  服务端API肯定不会修改了，Bmob几十个SDK，目前返回都是这个类型，如果单独改，其他语言用户就会受到影响。
