### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by npmrun** [bmob/hydrogen-js-sdk#81]
没人维护了吗
![image](https://user-images.githubusercontent.com/62639956/139443824-c2edbf99-c9dd-462a-8181-66c01606885e.png)
我是按流程做的：
```
npm install hydrogen-js-sdk 
Bmob.initialize("你的Secret Key", "你的API 安全码");
```
然后就报错了

**Comment by SakuNight** [comment]
(window as any).global = window

**Comment by magic007** [comment]
> 没人维护了吗 ![image](https://user-images.githubusercontent.com/62639956/139443824-c2edbf99-c9dd-462a-8181-66c01606885e.png) 我是按流程做的：
> 
> ```
> npm install hydrogen-js-sdk 
> Bmob.initialize("你的Secret Key", "你的API 安全码");
> ```
> 
> 然后就报错了

你这是什么环境下

**Comment by npmrun** [comment]
> > 没人维护了吗 ![image](https://user-images.githubusercontent.com/62639956/139443824-c2edbf99-c9dd-462a-8181-66c01606885e.png) 我是按流程做的：
> > ```
> > npm install hydrogen-js-sdk 
> > Bmob.initialize("你的Secret Key", "你的API 安全码");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后就报错了
> 
> 你这是什么环境下

浏览器环境啊

**Comment by longer96** [comment]
https://github.com/vitejs/vite/issues/2618

vite版本环境导致

**Comment by npmrun** [comment]
谢谢，是用的vite

**Comment by longer96** [comment]
For reference, if you only need to shim global, you can add

<script>window.global = window;</script>
to your index.html
