### ISSUE TITLE
如何查询（a=1 and b=1） or c=2 的结果

### ISSUE THREAD

**Issue by ehcsa** [bmob/hydrogen-js-sdk#9]
文档里 或查询，是这样的：
const query = Bmob.Query("tableName");
const query1 = query.equalTo("isLike", '>', 150);
const query2 = query.equalTo("isLike", '<', 150);

query.or(query1, query2);
query.find().then(res => {
  // 返回 isLike > 150 or isLike < 5 的值
  console.log(res)
});
如何给query1 添加一个and条件

**Comment by yanghuanrong** [comment]
const query = Bmob.Query("tableName");
const query1 = query.equalTo("a", '==', 1);
const query2 = query.equalTo("b", '==', 1);
const query3 = query.equalTo("c", '==', 2);
query.and(query1, query2);
query.or(query3);
query.find().then(res => {
console.log(res)
});

**Comment by ehcsa** [comment]
谢谢

**Comment by yanghuanrong** [comment]
那估计这里有个bug，谢谢你的反馈，这边及时修复一下，耽误你的时间了。
